// <auto-generated />
using BillingCycleAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BillingCycleAPI.Migrations
{
    [DbContext(typeof(BillingCycleContext))]
    partial class BillingCycleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("BillingCycleAPI.Models.BillingCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BillingCycles");
                });

            modelBuilder.Entity("BillingCycleAPI.Models.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<int>("billingCycleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("billingCycleId");

                    b.ToTable("Creditos");
                });

            modelBuilder.Entity("BillingCycleAPI.Models.Debit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<int>("billingCycleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("billingCycleId");

                    b.ToTable("Debitos");
                });

            modelBuilder.Entity("BillingCycleAPI.Models.Credit", b =>
                {
                    b.HasOne("BillingCycleAPI.Models.BillingCycle", "BillingCycle")
                        .WithMany("Creditos")
                        .HasForeignKey("billingCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillingCycle");
                });

            modelBuilder.Entity("BillingCycleAPI.Models.Debit", b =>
                {
                    b.HasOne("BillingCycleAPI.Models.BillingCycle", "BillingCycle")
                        .WithMany("Debitos")
                        .HasForeignKey("billingCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillingCycle");
                });

            modelBuilder.Entity("BillingCycleAPI.Models.BillingCycle", b =>
                {
                    b.Navigation("Creditos");

                    b.Navigation("Debitos");
                });
#pragma warning restore 612, 618
        }
    }
}
